name: build

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_IO_USERNAME }}
          password: ${{ secrets.DOCKER_IO_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Run Docker Buildx
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --push -t "raftt/nodetaint:${{ github.ref_name }}" .

      - uses: azure/setup-helm@v3

      - name: Login to GHCR
        shell: bash
        run: echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io/rafttio --username ${{ github.actor }} --password-stdin

      - name: Generate Helm chart version
        id: helm_chart_version
        shell: bash
        run: |
          # Helm chart versions should not contain the 'v' prefix
          export TAG="${{ github.ref_name }}"
          echo "chart_version=${TAG#v}" >> $GITHUB_OUTPUT

      - name: Helm Package
        shell: bash
        run: helm package chart/ --version ${{ steps.helm_chart_version.outputs.chart_version }} --app-version ${{ github.ref_name }}

      - name: Helm Push
        shell: bash
        run: helm push nodetaint-${{ steps.helm_chart_version.outputs.chart_version }}.tgz oci://ghcr.io/rafttio

